# Generated by Django 3.0.5 on 2020-04-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
