# Generated by Django 3.0.5 on 2020-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0002_delete_logmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
    ]
