# Generated by Django 3.0.5 on 2020-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_statedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
    ]
